# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.cache/wt [current_project]
set_property parent.project_path C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/test.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/start_page.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/background_mem.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/ani0.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/ani1.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/ani3.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/ani5.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/ani2.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/ani4.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/Desktop/2026/verilog_final.srcs/sources_1/new/ps0.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/Desktop/2026/verilog_final.srcs/sources_1/new/select.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/Desktop/2026/verilog_final.srcs/sources_1/new/ps1.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/Desktop/verilog_final/verilog_final.srcs/sources_1/new/p2.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/Desktop/verilog_final/verilog_final.srcs/sources_1/new/p4.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/Desktop/verilog_final/verilog_final.srcs/sources_1/new/play3.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/Desktop/verilog_final/verilog_final.srcs/sources_1/new/play0.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/Desktop/verilog_final/verilog_final.srcs/sources_1/new/play5.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/p1_win.mem
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/p2_win.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/Main.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/Desktop/Oled_Display_1.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/ball_pos.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/ball_state.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/button_press.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/collision_ball.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/collision_p.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/debouncer.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/debouncer_k.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/get_coord.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/get_coordinates.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/match_counter.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/movement_state.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/my_clock.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/p2_pos.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/placement.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/slow_clock.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/stateSet.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/imports/new/update_square_pos.v
  C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/sources_1/new/TopStudent.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Nero/Downloads/logveri.xpr/verilog_final/verilog_final.srcs/constrs_1/new/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top TopStudent -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TopStudent.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TopStudent_utilization_synth.rpt -pb TopStudent_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
